---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-chart
  namespace: ${CODESNACKS_NAMESPACE}
spec:
  values:
    fullnameOverride: weather-api-git-prod
    releaseName: weather-api-git-prod
    image:
      tag: v1
    ingress:
      rules:
        -
          paths:
            - path: /
              pathType: Prefix