---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: codesnacks-api
  namespace: ${CODESNACKS_NAMESPACE}
spec:
  interval: 5m
  chart:
    spec:
      chart:
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: ecr-chart
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
     repository: docker.io/codesnacks/weather
    persistence:
      enabled: true
      storageClassName: triden-default
      reclaimPolicy: Retain
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$2
