apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ecr-chart
  namespace: flux-system
spec:
  type: oci
  interval: 5m0s
  url: oci://722647055695.dkr.ecr.us-west-2.amazonaws.com