apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weather-chart
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/derekadombek/codesnacks
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/   