apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weather-chart
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/derekadombek/codesnacks
  ref:
    branch: main
  secretRef:
    name: flux-system
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deployment/charts/   