apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-prod
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: infrastructure-prod
  sourceRef:
    kind: GitRepository
    name: codesnacks-prod
  path: ./deployment/apps/prod
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      CODESNACKS_NAMESPACE: "codesnacks-prod"
    substituteFrom:
      - kind: ConfigMap
        name: prod-config