---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: ${CODESNACKS_NAMESPACE}
spec:
  values:
    fullnameOverride: vault-prod
    releaseName: vault-prod