---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: ${CODESNACKS_NAMESPACE}
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      # version: 0.20.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 1m
  values:
    csi:
      enabled: true
    server:
      dev:
        enabled: true
      service:
        type: NodePort
        nodePort: 30000