---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ecr-weather-chart
  namespace: ${CODESNACKS_NAMESPACE}
spec:
  interval: 1m
  chart:
    spec:
      chart: helm/weather-chart
      version: 0.1.3
      sourceRef:
        kind: HelmRepository
        name: ecr-weather-chart
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 3
  values:
    image:
     repository: docker.io/codesnacks/weather
    persistence:
      enabled: true
      storageClassName: triden-default
      reclaimPolicy: Retain
    service:
      type: ClusterIP
    secretName: aws-creds
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$2
